tests - exceptiontester
testSimpleOuter
	self assertSuccess: (ExceptionTester new runTest: #simpleOuterTest ) 